In [1]:
import numpy as np
import pandas as pd
import sklearn
 



In [11]:
from sklearn.datasets  import load_boston
df = load_boston()

In [12]:
df.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [16]:
print(df.data)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]


In [23]:
boston['SHINCHAN'] = df.target
boston.head(10)

CRIM    ZN  INDUS  CHAS    NOX  ...       B  LSTAT  MEDV  MARIO  SHINCHAN
0  0.00632  18.0   2.31   0.0  0.538  ...  396.90   4.98  24.0   24.0      24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  396.90   9.14  21.6   21.6      21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  392.83   4.03  34.7   34.7      34.7
3  0.03237   0.0   2.18   0.0  0.458  ...  394.63   2.94  33.4   33.4      33.4
4  0.06905   0.0   2.18   0.0  0.458  ...  396.90   5.33  36.2   36.2      36.2
5  0.02985   0.0   2.18   0.0  0.458  ...  394.12   5.21  28.7   28.7      28.7
6  0.08829  12.5   7.87   0.0  0.524  ...  395.60  12.43  22.9   22.9      22.9
7  0.14455  12.5   7.87   0.0  0.524  ...  396.90  19.15  27.1   27.1      27.1
8  0.21124  12.5   7.87   0.0  0.524  ...  386.63  29.93  16.5   16.5      16.5
9  0.17004  12.5   7.87   0.0  0.524  ...  386.71  17.10  18.9   18.9      18.9

[10 rows x 16 columns]

In [24]:
boston.isnull()

CRIM     ZN  INDUS   CHAS    NOX  ...      B  LSTAT   MEDV  MARIO  SHINCHAN
0    False  False  False  False  False  ...  False  False  False  False     False
1    False  False  False  False  False  ...  False  False  False  False     False
2    False  False  False  False  False  ...  False  False  False  False     False
3    False  False  False  False  False  ...  False  False  False  False     False
4    False  False  False  False  False  ...  False  False  False  False     False
..     ...    ...    ...    ...    ...  ...    ...    ...    ...    ...       ...
501  False  False  False  False  False  ...  False  False  False  False     False
502  False  False  False  False  False  ...  False  False  False  False     False
503  False  False  False  False  False  ...  False  False  False  False     False
504  False  False  False  False  False  ...  False  False  False  False     False
505  False  False  False  False  False  ...  False  False  False  False     False

[506 rows x 16 columns]

In [25]:
boston.isnull().sum()

CRIM        0
ZN          0
INDUS       0
CHAS        0
NOX         0
RM          0
AGE         0
DIS         0
RAD         0
TAX         0
PTRATIO     0
B           0
LSTAT       0
MEDV        0
MARIO       0
SHINCHAN    0
dtype: int64

In [37]:
from sklearn.model_selection import train_test_split
X = boston.drop('SHINCHAN',axis=1)
Y = boston['SHINCHAN']
X_train, X_test,Y_train, Y_test = train_test_split(X, Y, test_size = 0.15, random_state = 5)

print(X_train.shape)                     
print(X_test.shape)                    
print(Y_train.shape)
print(Y_test.shape)

 

(430, 15)
(76, 15)
(430,)
(76,)


In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [39]:
lin_model = LinearRegression()
lin_model.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [41]:
y_train_predict = lin_model.predict(X_train)
rmse = (np.sqrt(mean_squared_error(Y_train, y_train_predict)))
print("The model performance for training set")
print('RMSE is {}'.format(rmse))
print("\n")

#on testing set

y_test_predict = lin_model.predict(X_test)
rmse = (np.sqrt(mean_squared_error(Y_test, y_test_predict)))

print("The model prformance for testing set")
print('RMSE is {}'.format(rmse))

The model performance for training set
RMSE is 4.833059583041917e-14


The model prformance for testing set
RMSE is 5.5945686327907773e-14
